version:"3"

services:
  web:
    container_name: admin-op
    restart: always
    build: .
    ports:
      -"5000":"3000"
    links:
      -mongo
    volumes:
      - .:/usr/src/app
  mongo:
    conainer_name: mongodatabase
    image: mongo
    ports:
      -"27017":"27018"
    logging:
      driver: none